menu:
  归档: /archives
rss: /atom.xml
description:
social:
  weibo: http://weibo.com/xmwjn
  github: https://github.com/carnivalo
  stack_overflow:
  facebook:
  twitter: 
  google_plus: 
  instagram: 

page_comment: true
logo: /images/logo.png
background:
  cover: https://placem.at/things?w=1250&random=1
  color: cover-light-blue

fancybox: true

cloudtie_productkey: 

google_analytics: UA-73055515-1

favicon: /images/favicon.png

apple_touch_icon: /images/apple-touch-icon.png
